<?php

namespace Extensions\Plugins\Staff_alfiory__899612438\App\Models;

use Geeky\Database\CacheQueryBuilder;
use Illuminate\Database\Eloquent\Model;

class StaffAlfioryRank extends Model
{
    use CacheQueryBuilder;

    protected $table = 'staff_alfiory__ranks';
    protected $fillable = ['name', 'color', 'updated_at'];

    public function create(array $attributes = [])
    {
        return parent::create($attributes); // TODO: Change the autogenerated stub
    }
}
